<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9B2JCSO" failures="1" tests="6" name="Test 2" time="53.499" errors="0" timestamp="2023-10-27T11:41:34 IST">
  <testcase classname="org.testngpractice.Sample" name="tcs_1" time="11.159"/>
  <testcase classname="org.testngpractice.SampeTest" name="tc1_1" time="5.439"/>
  <testcase classname="org.testngpractice.SampeTest" name="tc1_2" time="8.832">
    <skipped/>
  </testcase> <!-- tc1_2 -->
  <testcase classname="org.testngpractice.SampeTest" name="tc1_2" time="7.842">
    <skipped/>
  </testcase> <!-- tc1_2 -->
  <testcase classname="org.testngpractice.SampeTest" name="tc1_2" time="6.953">
    <skipped/>
  </testcase> <!-- tc1_2 -->
  <testcase classname="org.testngpractice.SampeTest" name="tc1_2" time="13.032">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- tc1_2 -->
</testsuite> <!-- Test 2 -->
